parser: babel-eslint

plugins:
  - flowtype
  - prettier

extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - plugin:prettier/recommended

env:
  node: true
  browser: false

rules:

  prettier/prettier: error

  no-multi-assign: off

  no-return-assign:
    - error
    - except-parens

  no-confusing-arrow: off

  consistent-return: off

  no-unused-expressions: off

  object-curly-newline:
    - error
    - consistent: true

  function-paren-newline:
    - error
    - consistent

  import/prefer-default-export: off


  flowtype/boolean-style:
    - error
    - boolean

  flowtype/define-flow-type: error

  flowtype/delimiter-dangle:
    - error
    - always-multiline

  flowtype/generic-spacing:
    - error
    - never

  flowtype/no-dupe-keys: error

  flowtype/no-primitive-constructor-types: error

  flowtype/no-weak-types:
    - error
    - any: false
      Object: false
      Function: true

  flowtype/object-type-delimiter:
    - error
    - comma

  flowtype/require-valid-file-annotation:
    - error
    - never
    - annotationStyle: block

  flowtype/space-after-type-colon:
    - error
    - always
    - allowLineBreak: false

  flowtype/space-before-generic-bracket:
    - error
    - never

  flowtype/space-before-type-colon:
    - error
    - never

  flowtype/type-id-match:
    - error
    - ^[A-Z]

  flowtype/union-intersection-spacing:
    - error
    - always

  flowtype/use-flow-type: error
